[project]
name = "devrel-io"
version = "0.1.0"
description = "DevRel I/O"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "anthropic>=0.75.0",
    "boto3>=1.42.24",
    "chatlas[bedrock-anthropic]>=0.15.0",
    "itables[widget]>=2.6.1",
    "marimo>=0.19.0",
    "polars>=1.35.2",
    "pydantic-ai>=1.40.0",
    "querychat>=0.3.0",
    "shiny>=1.5.0",
    "shinywidgets>=0.7.0",
    "sqlglot>=28.5.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
