[project]
name = "devrel-io"
version = "0.1.0"
description = "DevRel I/O"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "google-analytics-data>=0.19.0",
    "google-auth-httplib2>=0.2.1",
    "google-auth-oauthlib>=1.2.3",
    "itables[widget]>=2.6.1",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "shiny>=1.5.0",
    "shinywidgets>=0.7.0",
]

[project.scripts]
gsheet = "gsheet:main"

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
